#!/bin/bash

set -e

#platforms="lin win mac" # for get all types of installation
#langs_priority="deu eng" # If German lang isn't available - get English
##Available lang in ISO 639-3: deu eng spa por tur fra ita pol ron fin swe ces rus zho jpn kor

platforms="${platforms:-lin win}"
langs_priority="${langs_priority:-rus eng}"
outpath=${outpath:-/var/www}


[ "$(dpkg -l | awk '{print $2}' | grep -c "^jq$")" -ne 1 ] && apt-get --yes install jq

function exit_script {
  set +x
  unset err_stat
  case $1 in
    err)  shift; echo -e "\033[1;33mError!\n${@}\033[0m"; err_stat=yes ;;
    warn) shift; echo -e "\033[1;34mError!\n${@}\033[0m";;
    info) shift; echo -e "$@" ;;
  esac
  [ -z "${err_stat}" ] && exit 0
  [ -n "${err_stat}" -a "${err_stat}" = yes ] && exit 1
}

[ -f gog_cook ] && cook=$(cat gog_cook) || exit_script err "NULL COOKIE!"

getpage() {
  [ -z "${1}" ] && exit_script err "NULL URL"
  curl -s -H "${cook}" "$(for i in $*; do echo -n "${i} "; done)"
}

totalpages="$(getpage "https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&mediaType=1" | jq -r '.totalPages')"

for i in $(seq 1 ${totalpages}); do
  inventory="$(echo -e "${inventory}${inventory:+\n}$(getpage "https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&mediaType=1&page=${i}&sortBy=date_purchased" | jq -r '.products[] | "\(.id) \(.slug) \(.title)"')")"
done

echo -e "${inventory}" | grep -v "^$" | while read id slug name; do
  unset lang_selected
  gameinfo="$(getpage "https://www.gog.com/account/gameDetails/${id}.json")"
  cdkey=$(echo ${gameinfo} | jq -r '.cdKey')
  langs_available=$(echo ${gameinfo} | jq -r '.downloads[] | .[0]')

  for lang in ${langs_priority,,}; do
    [ "${lang:0:3}" = rus ] && lang="русский"
    [ "${lang:0:3}" = eng ] && lang="English"
    [ "${lang:0:3}" = deu ] && lang="Deutsch"
    [ "${lang:0:3}" = spa ] && lang="Español (AL) or español"
    [ "${lang:0:3}" = por ] && lang="Português do Brasil or português"
    [ "${lang:0:3}" = tur ] && lang="Türkçe"
    [ "${lang:0:3}" = fra ] && lang="français"
    [ "${lang:0:3}" = ita ] && lang="italiano"
    [ "${lang:0:3}" = pol ] && lang="polski"
    [ "${lang:0:3}" = ron ] && lang="română"
    [ "${lang:0:3}" = fin ] && lang="suomi"
    [ "${lang:0:3}" = swe ] && lang="svenska"
    [ "${lang:0:3}" = ces ] && lang="český"
    [ "${lang:0:3}" = zho ] && lang="中文(简体)"
    [ "${lang:0:3}" = jpn ] && lang="日本語"
    [ "${lang:0:3}" = kor ] && lang="한국어"
    if [ "${lang}" = "Español (AL) or español" -o "${lang}" = "Português do Brasil or português" ]; then
      for i in $(echo ${lang// /_} | sed 's/_or_/ /g'); do
        [[ "${langs_available}" == *${i//_/ }* ]] && lang_selected=${i//_/ }
      done
    elif [[ "${langs_available,,}" == *"$(echo ${lang,,} | sed 's/ .*//g')"* ]]; then
      lang_selected=${lang}
    fi
    [ -n "${lang_selected}" ] && break
  done

  if [ -n "${lang_selected}" ]; then
    platform_available=$(echo ${gameinfo} | jq -r '.downloads[] | select(.[0]=="'${lang_selected}'") | .[1] | keys[]')
    for os in ${platforms,,}; do
      unset os_type
      [ "${os:0:1}" = l ] && os_type=linux
      [ "${os:0:1}" = w ] && os_type=windows
      [ "${os:0:1}" = m ] && os_type=mac
      if [[ "${platform_available}" == *${os_type}* ]]; then
        files_links=$(echo ${gameinfo} | jq -r '.downloads[] | select(.[0]=="'${lang_selected}'") | .[1] | .'${os_type}'[] | .manualUrl' | grep installer[0-9])
        files_count=$(echo -e "${files_links}" | wc -l)
        [ "${files_count}" -eq 1 ] && outdir=${outpath}/GOG/${os} || outdir=${outpath}/GOG/${os}/${slug}
        mkdir -p ${outdir}
        [ -n "${cdkey}" ] && echo ${cdkey} > ${outdir}/${slug}.cdkey
        unset count_download
        for i in ${files_links}; do
          count_download=$((count_download+1))
          echo -n "${name} [${os}] (${count_download}/${files_count}).. "
          target_link=$(curl -sILH "${cook}" --write-out '%{url_effective}' --output /dev/null https://www.gog.com${i})
          outfile_name=$(echo ${target_link} | sed 's/.*\///;s/%[0-9][0-9]//g;s/setup_//g;s/gog_//g;s///g;s/\.exe.*/.exe/g;s/\.bin.*/.bin/g')
          wget ${target_link} -qcO ${outdir}/${outfile_name}
          [ "$?" = 0 ] && echo ok || echo fail
        done
      fi
    done
  else
    echo ${name} is not available in languages ${langs_priority}!
  fi
done
