#!/bin/bash

for url in $(cat links); do
  filename=$(echo ${url} | sed 's/.*\///;s/%[0-9][0-9]//g;s/setup_//g;s/gog_//g')
  #trap "{ rm ${filename}.tmp; exit 0; }" EXIT
  echo -n "${filename}.. "
  [ "$(echo ${filename} | sed 's/^.*\.//g')" = exe -o "$(echo ${filename} | sed 's/^.*\.//g')" = bin ] && filename=win/${filename}
  [ "$(echo ${filename} | sed 's/^.*\.//g')" = sh ] && filename=lin/${filename}
  if [ "$(curl -I --write-out '%{http_code}' --silent --output /dev/null ${url})" = 200 -o "$(curl -I --write-out '%{http_code}' --silent --output /dev/null ${url})" = 301 ]; then
    if [ -f ${filename} ]; then
      if [ "$(curl -sI ${url} | tr -d '\r'  | tr '[:upper:]' '[:lower:]' | awk '/content-length/ {print $2}')" -gt "$(du -b ${filename} | awk '{print $1}')" ]; then
#        echo -n "delete.. "
#        rm ${filename}
        wget ${url} -qcO ${filename}.tmp
        if [ "$?" = 0 ]; then
          mv ${filename}.tmp ${filename}
          echo redownload
        else
          echo fail
        fi
      else
        echo skip
      fi
    else
      wget ${url} -qcO ${filename}.tmp
      mv ${filename}.tmp ${filename}
      echo done
    fi
  else
    echo bad url
  fi
done
