#!/bin/bash
# Generating playlists of video files in nested directories for videojs (videojs.com)
set -e

video_formats="mp4\|mpg\|ts\|mov\|m4v"

video_dirs="$(find "$(pwd)" -type f -iregex ".+\.\(${video_formats}\)" -exec dirname "{}" \; | sort -u)"

for dir in $(echo -e "${video_dirs}" | sed 's/ /✖✚/g'); do
  echo -n "$(realpath "$(echo ${dir} | sed 's/✖✚/ /g')")..  "
  dir_o="$(realpath "$(echo ${dir} | sed 's/✖✚/ /g')")"
  videos=$(find "${dir_o}" -maxdepth 1 -type f -iregex ".+\.\(${video_formats}\)" -exec basename {} \;)
  [ ! -d "${dir_o}/.meta" ] && mkdir -p "${dir_o}/.meta"
  cat << EOF > "${dir_o}/.playlist.js"
var player = videojs('video');

player.playlist([
$(for i in $(echo -e "${videos}" | sed 's/ /✖✚/g' | sort); do
  video_duration=$(ffprobe -i "${dir_o}/$(echo ${i} | sed 's/✖✚/ /g')" -v error -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 | head -n1)
  [ ! -f "${dir_o}/.meta/$(echo ${i} | sed 's/✖✚/ /g').png" ] && \
  ffmpeg -i "${dir_o}/$(echo ${i} | sed 's/✖✚/ /g')" -v error -ss 00:02:14.435 -frames:v 1 -filter:v scale="400:-1" "${dir_o}/.meta/$(echo ${i} | sed 's/✖✚/ /g').png"

  echo -e "    {  name: '$(echo ${i} | sed 's/✖✚/ /g')',"
  echo -e "       description: '${video_desc}',"
  echo -e "       duration: ${video_duration},"
  echo -e "       thumbnail: [{srcset: '.meta/$(echo ${i} | sed 's/✖✚/ /g').png', type: 'image/jpeg', media: '(min-width: 400px;)'}, {src: '.meta/$(echo ${i} | sed 's/✖✚/ /g').png'}],"
  echo -e "       sources: [{src: '$(echo ${i} | sed 's/✖✚/ /g')', type: 'video/mp4'}],"
  echo -e "       poster: '.meta/$(echo ${i} | sed 's/✖✚/ /g').png'"
  echo -e "    },"
done)
]);

// Play through the playlist automatically.
player.playlist.autoadvance(0);
EOF
  echo ok
done
