#!/bin/bash
# Generating playlists of audio files in nested directories for webamp (webamp.org)
set -e

audio_formats="mp3\|wav\|flac\|m4a"

track_dirs="$(find "$(pwd)" -type f -regex ".+\.\(${audio_formats}\)" -exec dirname "{}" \; | sort -u)"

for dir in $(echo -e "${track_dirs}" | sed 's/ /✖✚/g'); do
  echo -n "$(realpath "$(echo ${dir} | sed 's/✖✚/ /g')")..  "
  dir_o="$(realpath "$(echo ${dir} | sed 's/✖✚/ /g')")"
  mp3s=$(find "${dir_o}" -maxdepth 1 -type f -regex ".+\.\(${audio_formats}\)" -exec basename {} \;)
  cat << EOF > "${dir_o}/.webamp.js"
const Webamp = window.Webamp;
const webamp = new Webamp({
initialTracks: [
$(for i in $(echo -e "${mp3s}" | sed 's/ /✖✚/g' | sort); do
  track_duration=$(ffprobe -i "${dir_o}/$(echo ${i} | sed 's/✖✚/ /g')" -v error -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 | head -n1)
  track_artist=$(ffprobe -i "${dir_o}/$(echo ${i} | sed 's/✖✚/ /g')" -v error -show_entries format_tags=artist -of default=noprint_wrappers=1:nokey=1 | head -n1 | sed 's/"//g')
  track_title=$(ffprobe -i "${dir_o}/$(echo ${i} | sed 's/✖✚/ /g')" -v error -show_entries format_tags=title -of default=noprint_wrappers=1:nokey=1 | head -n1 | sed 's/"//g')

  [ -z "${track_artist}" ] && track_artist=$(echo ${i} | sed 's/✖✚/ /g')
  [ -z "${track_title}" ]  && track_title=" "

  echo -e "  {"
  [ -n "${track_artist}" -o -n "${track_title}" ] && \
  echo -e "    metaData: {\n      ${track_artist:+artist: \"}${track_artist}${track_artist:+\",}\n      ${track_title:+title: \"}${track_title}${track_title:+\"}},"
  echo -e "    url: \"$(echo ${i} | sed 's/✖✚/ /g')\",\n    duration: ${track_duration}\n  },"
  unset track_duration track_artist track_title
done)
],
});
// Returns a promise indicating when it's done loading.
webamp.renderWhenReady(document.getElementById('app'));
EOF
  echo ok
done
