#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source=$(echo ${1} | sed 's/\/$//g')

for i in $(curl -s ${1} | grep href | grep -v "/\"" | sed 's/.*href=\"//g;s/\".*//g'); do
  echo ${source}/${i}
done > links
bash ${SCRIPT_DIR}/geter
